import * as React from "react";
import { Heading, Section, Text } from "@react-email/components";
import { EmailLayout, C, font } from "./_components/EmailLayout";

export interface MagicLinkEmailProps {
  recipientName?: string;
  /** 6-digit OTP code generated by WorkOS */
  code: string;
  expiresInMinutes?: number;
}

export default function MagicLinkEmail({
  recipientName,
  code,
  expiresInMinutes = 15,
}: MagicLinkEmailProps) {
  const greeting = recipientName ? `Hi ${recipientName},` : "Hi there,";

  return (
    <EmailLayout preview={`Your GROE sign-in code: ${code}`}>
      <Heading
        as="h1"
        style={{
          fontFamily: font.heading,
          fontWeight: 700,
          fontSize: "22px",
          color: C.heading,
          margin: "0 0 20px",
          lineHeight: "1.3",
        }}
      >
        Your sign-in code
      </Heading>

      <Text style={{ color: C.body, fontSize: "15px", lineHeight: "1.6", margin: "0 0 8px", fontFamily: font.body }}>
        {greeting}
      </Text>
      <Text style={{ color: C.body, fontSize: "15px", lineHeight: "1.6", margin: "0 0 24px", fontFamily: font.body }}>
        Use the code below to sign in to GROE. It works once and expires in{" "}
        <strong>{expiresInMinutes} minutes</strong>.
      </Text>

      {/* OTP code display */}
      <Section
        style={{
          backgroundColor: C.bg,
          borderRadius: "8px",
          padding: "24px 16px",
          textAlign: "center",
          margin: "0 0 24px",
          border: `1px solid ${C.border}`,
        }}
      >
        <Text
          style={{
            fontFamily: font.mono,
            fontWeight: 700,
            fontSize: "42px",
            letterSpacing: "14px",
            color: C.heading,
            margin: 0,
            lineHeight: "1",
          }}
        >
          {code}
        </Text>
      </Section>

      <Text style={{ color: C.muted, fontSize: "13px", lineHeight: "1.5", margin: 0, fontFamily: font.body }}>
        If you didn&apos;t request this code, you can safely ignore this email.
        Someone may have entered your email address by mistake.
      </Text>
    </EmailLayout>
  );
}

MagicLinkEmail.PreviewProps = {
  recipientName: "Alex Chen",
  code: "847291",
  expiresInMinutes: 15,
} satisfies MagicLinkEmailProps;
