import { NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/server";
import { requireRole } from "@/lib/auth/session";
import { ProvisionOrgSchema } from "@/lib/validators/groe-admin";
import { logAuditEvent, AuditAction } from "@/lib/audit";
import { sendEmail } from "@/lib/email/send";
import OrgAdminInviteEmail from "@/emails/org-admin-invite";
import React from "react";

const APP_URL = process.env.NEXT_PUBLIC_APP_URL!;

// ---------------------------------------------------------------------------
// GET /api/groe-admin/orgs — list all orgs with aggregate stats
// ---------------------------------------------------------------------------
export async function GET(request: Request) {
  try {
    const actor = await requireRole("groe_admin", "groe_viewer");
    const db = createAdminClient();

    const { data: orgs, error } = await db
      .from("orgs")
      .select(`
        id, name, slug, is_active, created_at,
        users:users(count)
      `)
      .order("created_at", { ascending: false });

    if (error) {
      console.error("[groe-admin/orgs GET]", error);
      return NextResponse.json({ error: "Failed to fetch orgs" }, { status: 500 });
    }

    void actor; // used implicitly via requireRole access check
    return NextResponse.json({ orgs });
  } catch (response) {
    if (response instanceof Response) return response;
    throw response;
  }
}

// ---------------------------------------------------------------------------
// POST /api/groe-admin/orgs — provision a new org + invite the Org Admin
// ---------------------------------------------------------------------------
export async function POST(request: Request) {
  try {
    const actor = await requireRole("groe_admin");

    const body: unknown = await request.json();
    const parsed = ProvisionOrgSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json(
        { error: "Validation failed", issues: parsed.error.issues },
        { status: 400 }
      );
    }

    const { orgName, orgSlug, adminEmail, adminFullName } = parsed.data;
    const db = createAdminClient();

    // 1. Create org
    const { data: org, error: orgError } = await db
      .from("orgs")
      .insert({ name: orgName, slug: orgSlug })
      .select("id, name, slug")
      .single();

    if (orgError) {
      if (orgError.code === "23505") {
        return NextResponse.json(
          { error: "An org with that slug already exists" },
          { status: 409 }
        );
      }
      console.error("[groe-admin/orgs POST] org insert:", orgError);
      return NextResponse.json({ error: "Failed to create org" }, { status: 500 });
    }

    await logAuditEvent({
      action:       AuditAction.ORG_CREATED,
      userId:       actor.id,
      orgId:        org.id,
      targetType: "org",
      targetId:   org.id,
      request,
    });

    // 2. Create invite record — token generated by DB default
    const { data: invite, error: inviteError } = await db
      .from("org_invites")
      .insert({
        org_id:        org.id,
        email:         adminEmail,
        role:          "org_admin",
        invited_by_id: actor.id,
      })
      .select("token")
      .single();

    if (inviteError || !invite) {
      console.error("[groe-admin/orgs POST] invite insert:", inviteError);
      return NextResponse.json(
        { error: "Org created but invite could not be generated" },
        { status: 500 }
      );
    }

    // 3. Send invite email
    const inviteUrl = `${APP_URL}/accept-invite?token=${invite.token}`;
    await sendEmail({
      to:      adminEmail,
      subject: `You've been invited to manage ${orgName} on GROE`,
      react:   React.createElement(OrgAdminInviteEmail, {
        recipientName: adminFullName,
        orgName,
        inviterName:   "The GROE Team",
        inviteUrl,
        expiresInDays: 7,
      }),
    });

    await logAuditEvent({
      action:       AuditAction.ORG_INVITE_SENT,
      userId:       actor.id,
      orgId:        org.id,
      targetType: "org_invite",
      targetId:   org.id,
      request,
    });

    return NextResponse.json({ org }, { status: 201 });
  } catch (response) {
    if (response instanceof Response) return response;
    throw response;
  }
}
